apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: Model
metadata:
  name: <YOUR JOB NAME>
spec:
  modelName: <YOUR JOB NAME>
  primaryContainer:
    containerHostname: xgboost
    modelDataURL: s3://<YOUR BUCKET>/path
    # The source of the model data
    image: 433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1
    # The URL and tag of your ECR container  
    # If you are not on us-west-2 you can find an imageURI here https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-algo-docker-registry-paths.html
    environment:
      my_var: my_value
      my_var2: my_value2
  executionRoleARN: <YOUR SAGEMAKER ROLE ARN>
  # Example arn:aws:iam::1234567890:role/service-role/AmazonSageMaker-ExecutionRole